-- ==============================================================================
-- AltilloJVG - Configuración de Tablas Adicionales en Supabase (Versión 2)
-- Tablas: submissions (Peticiones de Subida) y news (Tablón de Noticias)
-- ==============================================================================

-- 1. Tabla de Peticiones de Subida de Materiales
CREATE TABLE IF NOT EXISTS public.submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  carrera TEXT NOT NULL,
  anio TEXT NOT NULL,
  materia TEXT NOT NULL,
  tipo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  link TEXT NOT NULL,
  estado TEXT DEFAULT 'pendiente', -- 'pendiente', 'aprobado', 'rechazado'
  aprobado_por TEXT,
  telegram_message_id BIGINT,
  telegram_chat_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS y Políticas para submissions
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read of submissions" ON public.submissions;
CREATE POLICY "Allow public read of submissions" ON public.submissions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow service_role full access to submissions" ON public.submissions;
CREATE POLICY "Allow service_role full access to submissions" ON public.submissions FOR ALL USING (true);

-- 2. Tabla del Tablón de Noticias / Novedades
CREATE TABLE IF NOT EXISTS public.news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  contenido TEXT NOT NULL,
  categoria TEXT DEFAULT 'Aviso', -- 'Aviso', 'Importante', 'Gremial', 'Urgente'
  autor TEXT DEFAULT 'La Caravana',
  fijado BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS y Políticas para news
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read of news" ON public.news;
CREATE POLICY "Allow public read of news" ON public.news FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow service_role full access to news" ON public.news FOR ALL USING (true);

-- 3. Noticia inaugural inicial (solo si la tabla está vacía)
INSERT INTO public.news (titulo, contenido, categoria, autor, fijado)
SELECT 
  '¡Bienvenidos al nuevo AltilloJVG!',
  'Compañeras y compañeros: lanzamos la versión renovada del repositorio digital estudiantil. Acá van a encontrar apuntes, resúmenes, programas y exámenes clasificados por carrera y año, además de buscadores de aulas y mapas de correlatividades. ¡Construyamos este espacio entre todos!',
  'Importante',
  'La Caravana + Estudiantes Independientes',
  true
WHERE NOT EXISTS (SELECT 1 FROM public.news LIMIT 1);
