-- ==============================================================================
-- AltilloJVG - Configuración de Tablas Adicionales en Supabase (Versión 2)
-- Tablas: submissions (Peticiones de Subida) y news (Tablón de Noticias)
-- ==============================================================================

-- 1. Tabla de Peticiones de Subida de Materiales
CREATE TABLE IF NOT EXISTS public.submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  carrera TEXT NOT NULL,
  anio TEXT NOT NULL,
  materia TEXT NOT NULL,
  tipo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  link TEXT NOT NULL,
  estado TEXT DEFAULT 'pendiente',
  aprobado_por TEXT,
  telegram_message_id BIGINT,
  telegram_chat_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'submissions' AND policyname = 'Public Read Submissions') THEN
    CREATE POLICY "Public Read Submissions" ON public.submissions FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'submissions' AND policyname = 'Service Role Submissions') THEN
    CREATE POLICY "Service Role Submissions" ON public.submissions FOR ALL USING (true);
  END IF;
END $$;

-- 2. Tabla del Tablón de Noticias
CREATE TABLE IF NOT EXISTS public.news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  contenido TEXT NOT NULL,
  categoria TEXT DEFAULT 'Aviso',
  autor TEXT DEFAULT 'La Caravana + Estudiantes Independientes',
  fijado BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'news' AND policyname = 'Public Read News') THEN
    CREATE POLICY "Public Read News" ON public.news FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'news' AND policyname = 'Service Role News') THEN
    CREATE POLICY "Service Role News" ON public.news FOR ALL USING (true);
  END IF;
END $$;

-- 3. Noticia inaugural inicial
INSERT INTO public.news (titulo, contenido, categoria, autor, fijado)
SELECT 
  '¡Bienvenidos al nuevo AltilloJVG!',
  'Compañeras y compañeros: lanzamos la versión renovada del repositorio digital estudiantil. Acá van a encontrar apuntes, resúmenes, programas y exámenes clasificados por carrera y año, además de buscadores de aulas y mapas de correlatividades. ¡Construyamos este espacio entre todos!',
  'Importante',
  'La Caravana + Estudiantes Independientes',
  true
WHERE NOT EXISTS (SELECT 1 FROM public.news LIMIT 1);
