-- AltilloJVG - Metricas y Telemetria Persistente (Version 4)
CREATE TABLE IF NOT EXISTS public.site_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric_type TEXT NOT NULL,
  metric_key TEXT NOT NULL,
  count BIGINT DEFAULT 1 NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(metric_type, metric_key)
);

ALTER TABLE public.site_metrics ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION increment_metric(m_type TEXT, m_key TEXT)
RETURNS void AS \$\$
BEGIN
  INSERT INTO public.site_metrics (metric_type, metric_key, count, updated_at)
  VALUES (m_type, m_key, 1, timezone('utc'::text, now()))
  ON CONFLICT (metric_type, metric_key)
  DO UPDATE SET
    count = public.site_metrics.count + 1,
    updated_at = timezone('utc'::text, now());
END;
\$\$ LANGUAGE plpgsql SECURITY DEFINER;
