-- ==============================================================================
-- AltilloJVG - Configuración de Tablas Adicionales en Supabase (Versión 3)
-- Tablas: subscribers (Lista de Difusión) y feedback (Buzón de Consultas)
-- ==============================================================================

-- 1. Tabla de Suscriptores al Tablón de Novedades
CREATE TABLE IF NOT EXISTS public.subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.subscribers ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'subscribers' AND policyname = 'Public Insert Subscribers') THEN
    CREATE POLICY "Public Insert Subscribers" ON public.subscribers FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'subscribers' AND policyname = 'Public Read Subscribers') THEN
    CREATE POLICY "Public Read Subscribers" ON public.subscribers FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'subscribers' AND policyname = 'Service Role Subscribers') THEN
    CREATE POLICY "Service Role Subscribers" ON public.subscribers FOR ALL USING (true);
  END IF;
END $$;

-- 2. Tabla del Buzón de Consultas y Sugerencias
CREATE TABLE IF NOT EXISTS public.feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT,
  carrera TEXT,
  tipo TEXT DEFAULT 'Sugerencia',
  mensaje TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'feedback' AND policyname = 'Public Insert Feedback') THEN
    CREATE POLICY "Public Insert Feedback" ON public.feedback FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'feedback' AND policyname = 'Service Role Feedback') THEN
    CREATE POLICY "Service Role Feedback" ON public.feedback FOR ALL USING (true);
  END IF;
END $$;
